sudo: required
services:
  - docker

before_install:
  - docker build -t surya15/test-mca -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true surya15/test-mca npm run test

after_success:
  - docker build -t surya15/mca-client ./client
  - docker build -t surya15/mca-nginx ./nginx
  - docker build -t surya15/mca-server ./server
  - docker build -t surya15/mca-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PSWD" | docker login -u "$DOCKER_ID" --password-stdin
  #Publish those images intp docker HUB
  - docker push surya15/mca-client
  - docker push surya15/mca-nginx
  - docker push surya15/mca-server
  - docker push surya15/mca-worker
